// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace GameEngine.Data
{
    using GameEngine.Model;

    // Config
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class ConfigConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Config>
    {
        public ConfigConfiguration()
            : this("dbo")
        {
        }

        public ConfigConfiguration(string schema)
        {
            ToTable(schema + ".Config");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.GaasCampaignKey).HasColumnName(@"Gaas_CampaignKey").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(128);
            Property(x => x.GaasPanelId).HasColumnName(@"Gaas_PanelId").IsRequired().HasColumnType("int");
            Property(x => x.ShowMenu).HasColumnName(@"ShowMenu").IsRequired().HasColumnType("bit");
            Property(x => x.ShowResult).HasColumnName(@"ShowResult").IsRequired().HasColumnType("bit");
            Property(x => x.LevelNumber).HasColumnName(@"LevelNumber").IsOptional().HasColumnType("int");
            Property(x => x.GameConfigJson).HasColumnName(@"GameConfigJson").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(2000);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
