// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace GameEngine.Data
{
    using GameEngine.Model;

    // GameEventData
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class GameEventDatumConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GameEventDatum>
    {
        public GameEventDatumConfiguration()
            : this("dbo")
        {
        }

        public GameEventDatumConfiguration(string schema)
        {
            ToTable(schema + ".GameEventData");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ConsumerId).HasColumnName(@"Consumer_ID").IsRequired().HasColumnType("int");
            Property(x => x.FuelId).HasColumnName(@"Fuel_ID").IsRequired().HasColumnType("int");
            Property(x => x.EventDate).HasColumnName(@"EventDate").IsRequired().HasColumnType("datetime");
            Property(x => x.DataJson).HasColumnName(@"DataJson").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(2000);

            // Foreign keys
            HasRequired(a => a.Consumer).WithMany(b => b.GameEventDatums).HasForeignKey(c => c.ConsumerId).WillCascadeOnDelete(false); // FK_GameEventData_Consumer
            HasRequired(a => a.Fuel).WithMany(b => b.GameEventDatums).HasForeignKey(c => c.FuelId).WillCascadeOnDelete(false); // FK_GameEventData_Fuel
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
