
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DodgeBall.Data
{

    using DodgeBall.Model;


    // Config

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class ConfigConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Config>
    {
        public ConfigConfiguration()
            : this("dbo")
        {
        }

        public ConfigConfiguration(string schema)
        {

            ToTable(schema + ".Config");

            HasKey(x => x.Id);


            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);

            Property(x => x.GaasCampaignKey).HasColumnName(@"Gaas_CampaignKey").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(128);

            Property(x => x.GaasPanelId).HasColumnName(@"Gaas_PanelId").IsRequired().HasColumnType("int");

            Property(x => x.ShowMenu).HasColumnName(@"ShowMenu").IsRequired().HasColumnType("bit");

            Property(x => x.ShowResult).HasColumnName(@"ShowResult").IsRequired().HasColumnType("bit");

            Property(x => x.LevelNumber).HasColumnName(@"LevelNumber").IsOptional().HasColumnType("int");

            Property(x => x.CutOffScore).HasColumnName(@"CutOffScore").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore1Low).HasColumnName(@"FBShare_Score1_Low").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore1High).HasColumnName(@"FBShare_Score1_High").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore1Msg).HasColumnName(@"FBShare_Score1_Msg").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareScore2Low).HasColumnName(@"FBShare_Score2_Low").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore2High).HasColumnName(@"FBShare_Score2_High").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore2Msg).HasColumnName(@"FBShare_Score2_Msg").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareScore3Low).HasColumnName(@"FBShare_Score3_Low").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore3High).HasColumnName(@"FBShare_Score3_High").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore3Msg).HasColumnName(@"FBShare_Score3_Msg").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareScore4Low).HasColumnName(@"FBShare_Score4_Low").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore4High).HasColumnName(@"FBShare_Score4_High").IsOptional().HasColumnType("int");

            Property(x => x.FbShareScore4Msg).HasColumnName(@"FBShare_Score4_Msg").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.CustomText).HasColumnName(@"CustomText").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);

            Property(x => x.FbShareName).HasColumnName(@"FBShare_Name").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareCaption).HasColumnName(@"FBShare_Caption").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareUrl).HasColumnName(@"FBShare_Url").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareScore1ImgUrl).HasColumnName(@"FBShare_Score1_ImgUrl").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareScore2ImgUrl).HasColumnName(@"FBShare_Score2_ImgUrl").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareScore3ImgUrl).HasColumnName(@"FBShare_Score3_ImgUrl").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);

            Property(x => x.FbShareScore4ImgUrl).HasColumnName(@"FBShare_Score4_ImgUrl").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);




            InitializePartial();
        }

        partial void InitializePartial();
    }



}
// </auto-generated>
