
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace PaperToss.Model
{





    // Fuel


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Fuel
    {




        public int Id { get; set; } // ID (Primary key)



        public int ConsumerId { get; set; } // Consumer_ID



        public System.DateTime Created { get; set; } // Created



        public System.DateTime? UtilizedDate { get; set; } // UtilizedDate



        public bool AutoDiscard { get; set; } // AutoDiscard



        // Reverse navigation


        public virtual System.Collections.Generic.ICollection<GamePlay> GamePlays { get; set; } // GamePlay.FK_GamePlay_Fuel




        public Fuel()
        {

            ConsumerId = 0;

            AutoDiscard = false;


            GamePlays = new System.Collections.Generic.List<GamePlay>();

            InitializePartial();
        }


        partial void InitializePartial();

    }



}
// </auto-generated>
