
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DodgeBall.Model
{





    // Scores


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Score
    {




        public int Id { get; set; } // ID (Primary key)



        public int? ConsumerId { get; set; } // Consumer_ID



        public System.DateTime Scored { get; set; } // Scored



        public int Result { get; set; } // Result




        // Foreign keys


        public virtual Consumer Consumer { get; set; } // FK_Scores_Consumer



        public Score()
        {


            InitializePartial();
        }


        partial void InitializePartial();

    }



}
// </auto-generated>
