// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace GameEngine.Model
{

    // Config
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Config
    {
        public int Id { get; set; } // ID (Primary key)
        public string GaasCampaignKey { get; set; } // Gaas_CampaignKey (length: 128)
        public int GaasPanelId { get; set; } // Gaas_PanelId
        public bool ShowMenu { get; set; } // ShowMenu
        public bool ShowResult { get; set; } // ShowResult
        public int? LevelNumber { get; set; } // LevelNumber
        public string GameConfigJson { get; set; } // GameConfigJson (length: 2000)

        public Config()
        {
            ShowMenu = false;
            ShowResult = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
