// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace GameEngine.Model
{

    // GameEventData
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class GameEventDatum
    {
        public int Id { get; set; } // ID (Primary key)
        public int ConsumerId { get; set; } // Consumer_ID
        public int FuelId { get; set; } // Fuel_ID
        public System.DateTime EventDate { get; set; } // EventDate
        public string DataJson { get; set; } // DataJson (length: 2000)

        // Foreign keys
        public virtual Consumer Consumer { get; set; } // FK_GameEventData_Consumer
        public virtual Fuel Fuel { get; set; } // FK_GameEventData_Fuel

        public GameEventDatum()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
