-- 20 Feb 2017
ALTER TABLE [dbo].[Consumer] DROP CONSTRAINT [IX_Consumer]
GO

ALTER TABLE [dbo].[Consumer] ALTER COLUMN Gaas_ConsumerId VARCHAR(450) NOT NULL
GO

ALTER TABLE [dbo].[Consumer] ADD  CONSTRAINT [IX_Consumer] UNIQUE NONCLUSTERED 
(
	[Gaas_CampaignKey] ASC,
	[Gaas_ConsumerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
GO
-- 20 Feb 2017
